AWSTemplateFormatVersion: "2010-09-09"
Description:
  This cfn file is used for creating a template which run S3 static web-hosting using cloudfrount distribution.

Parameters:
    pKittensDomain:
      Description: Domain name for kittens website 
      Type: String
      Default: mykittens.clarusway.us

Resources:
    rKittensBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Ref pKittensDomain
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        WebsiteConfiguration:
          IndexDocument: index.html
    
    rBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref rKittensBucket
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal: '*'
              Action: 
                -'s3:GetObjects'
              Resource: !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref rKittensBucket
                  - /*



# Outputs:
#   BucketName: 
    
#   CloudfrontEndpoint:
    
#   FullDomainName:
    